--- #YAML:1.0
name:               App-Cpan
version:            1.58_01
abstract:           Interact with CPAN from the command line
author:
    - brian d foy <bdfoy@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    CPAN:        1.9301
    Test::More:  0
no_index:
    directory:
        - t
        - inc
        - t
        - inc
        - examples
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
